window.TOPICS = [
  {
    id: 'procurement',
    title: 'Procurement & Purchasing',
    shortTitle: 'Procurement',
    description: 'Competitive solicitations, professional services, construction, audits, bonds, and purchasing thresholds.',
    icon: 'briefcase',
  },
  {
    id: 'sunshine',
    title: 'Sunshine & Public Meetings',
    shortTitle: 'Sunshine',
    description: 'Open meetings, notice, minutes, public comment, voting, and statutory exemptions.',
    icon: 'sun',
  },
  {
    id: 'public-records',
    title: 'Public Records',
    shortTitle: 'Records',
    description: 'Inspection, copying, exemptions, custodians, and contractor record obligations.',
    icon: 'files',
  },
  {
    id: 'cra',
    title: 'Community Redevelopment',
    shortTitle: 'CRAs',
    description: 'Creation, plans, powers, reporting, property disposition, and redevelopment trust funds.',
    icon: 'building',
  },
  {
    id: 'special-districts',
    title: 'Special Districts',
    shortTitle: 'Districts',
    description: 'Uniform accountability, websites, reporting, performance measures, and oversight.',
    icon: 'district',
  },
  {
    id: 'cdd',
    title: 'Community Development Districts',
    shortTitle: 'CDDs',
    description: 'District establishment, boards, powers, budgets, records, and infrastructure authority.',
    icon: 'map',
  },
  {
    id: 'ethics',
    title: 'Ethics & Voting Conflicts',
    shortTitle: 'Ethics',
    description: 'Standards of conduct, conflicts, gifts, voting requirements, and disclosures.',
    icon: 'scale',
  },
  {
    id: 'code-enforcement',
    title: 'Code Enforcement',
    shortTitle: 'Code',
    description: 'Enforcement procedure, hearings, fines, liens, notice, and appeals.',
    icon: 'shield',
  },
  {
    id: 'municipal',
    title: 'Municipal Government',
    shortTitle: 'Municipal',
    description: 'Home rule, ordinances, emergency measures, and core municipal powers.',
    icon: 'landmark',
  },
  {
    id: 'elections',
    title: 'Elections & Office',
    shortTitle: 'Elections',
    description: 'Municipal elections, resign-to-run, vacancies, qualification, and voting rules.',
    icon: 'vote',
  },
  {
    id: 'utilities-claims',
    title: 'Utilities, Claims & Risk',
    shortTitle: 'Utilities',
    description: 'Municipal utilities, sovereign immunity, claims notice, and related operational authority.',
    icon: 'droplet',
  },
  {
    id: 'property-towing',
    title: 'Property, Parking & Towing',
    shortTitle: 'Property',
    description: 'Private-property towing, public construction bonds, liens, and property-related procedures.',
    icon: 'car',
  },
]

window.CLIENTS = [
  {
    id: 'villages',
    name: 'The Villages',
    type: 'Special districts / local government',
    subtitle: 'District operations, procurement, meetings, records, ethics, and CDD authority.',
    focusTopics: ['special-districts', 'cdd', 'procurement', 'sunshine', 'public-records', 'ethics'],
  },
  {
    id: 'minneola',
    name: 'Minneola',
    type: 'Municipality',
    subtitle: 'Municipal authority, procurement, CRA, meetings, records, elections, and code enforcement.',
    focusTopics: ['municipal', 'procurement', 'cra', 'sunshine', 'public-records', 'elections', 'code-enforcement'],
  },
  {
    id: 'leesburg',
    name: 'Leesburg',
    type: 'Municipality',
    subtitle: 'Municipal operations, utilities, procurement, code enforcement, records, and towing issues.',
    focusTopics: ['municipal', 'utilities-claims', 'procurement', 'code-enforcement', 'public-records', 'sunshine', 'property-towing'],
  },
  {
    id: 'umatilla',
    name: 'Umatilla',
    type: 'Municipality',
    subtitle: 'Municipal authority, procurement, meetings, records, elections, and CRA matters.',
    focusTopics: ['municipal', 'procurement', 'sunshine', 'public-records', 'elections', 'cra', 'code-enforcement'],
  },
]
